# Generated by Django 5.1.2 on 2024-10-15 09:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ndvi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("growing_season", models.CharField(max_length=100)),
                ("ideal_ndvi_range", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="farm",
            name="ndvi_value",
        ),
        migrations.AddField(
            model_name="farm",
            name="irrigation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Drip", "Drip"),
                    ("Sprinkler", "Sprinkler"),
                    ("Flood", "Flood"),
                ],
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="size",
            field=models.FloatField(default=0.0, help_text="Farm size in hectares"),
        ),
        migrations.AddField(
            model_name="farm",
            name="soil_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="farm",
            name="crop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="farms",
                to="ndvi.crop",
            ),
        ),
        migrations.CreateModel(
            name="NDVIAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ndvi_value", models.FloatField()),
                ("analysis_date", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ndvi_readings",
                        to="ndvi.farm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField(help_text="Temperature in Celsius")),
                ("humidity", models.FloatField(help_text="Humidity percentage")),
                ("precipitation", models.FloatField(help_text="Precipitation in mm")),
                ("recorded_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_data",
                        to="ndvi.farm",
                    ),
                ),
            ],
        ),
    ]
